### ISSUE TITLE
We should not return ratings that are hidden when filters are applied to the `jobtitles` and `companies`

### ISSUE THREAD

**Issue by elhmn** [osscameroon/jobsika#197]
We hide `companies` and `jobtitles` for ratings that had less than 5 entries on #189 . 
But it seems that we still return hidden ratings when doing request with filters.

`curl -X GET https://api.jobsika.stage.osscameroon.com/ratings?page=1&limit=10&company=something&jobtitle=something`

Will return a list a ratings corresponding to the hidden filters

**Comment by DipandaAser** [comment]
I tried to reproduce the behavior. it works normally. 
Fields that need to be hide are, and as #128 say, field who need to be hide is only: 
- company_id, 
- company_name, 
- rating, 
- comment

jobtitles is not on the list.

**Comment by elhmn** [comment]
Here is a screenshot to illustrate what this bug is. Let's keep in mind that it would be nice to have a fix for this feature before the launch the 1st of May 2022

**Comment by elhmn** [comment]
Reopening as it is not working as expected

**Comment by DipandaAser** [comment]
@elhmn fixed now. check #328
