### ISSUE TITLE
Elements on the last row are not aligned

### ISSUE THREAD

**Issue by Theryx** [osscameroon/jobsika#340]
The elements in the last row of the table showing the averages are not aligned(See screenshot below). This can cause confusion if not taken care of.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/45546512/192061512-b071caf8-bc60-4912-be74-ed27a1b186af.png">

I suggest the elements in the table be aligned as in the image below. 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/45546512/192062058-3fc7490b-9f88-46cf-907d-cba199414509.png">

**Comment by mouafus** [comment]
Is some one working on ?? 
I'm free, i could

**Comment by Theryx** [comment]
No one is working on it yet. Please feel free to go ahead.

Thank you

**Comment by mouafus** [comment]
> 

I'm so sorry but i could not do it. I have clone the project before realize that front is make with vuejs, i don't know that, i don't want to make mistake. some one else can work on this issue.

Very sorry

**Comment by Theryx** [comment]
No worries thank you so much for trying.
