### ISSUE TITLE
Add design for the new job offer workflow

### ISSUE THREAD

**Issue by rakici** [osscameroon/jobsika#360]
- [x] Redesign the home page
- [x] Design of the job listing page
- [x] Design of the job listing page (Responsive)
- [x] Design of the job posting form
- [x] Paiement dialog, that is triggered when the job offer is submitted
- [x] Dialog for the job application (should show a short message or redirect to another url)

**Comment by Theryx** [comment]
See Figma Link here: https://www.figma.com/file/829aq4WfAAx5HUJRNa1z8r/Jobsika-team-library?node-id=0%3A1&t=Rj0ws9GenuY7mgO2-1
