### ISSUE TITLE
Come up with a list of fields for the job submission form

### ISSUE THREAD

**Issue by rakici** [osscameroon/jobsika#361]
We currently don't know what fields will be added to the job submission form. We then 
need to spend some time figuring out what to add there.

Some work was done on this [issue](https://github.com/osscameroon/jobsika/pull/354) to set  up the DB fields, so it provides us with some data to start with.

**Comment by wdjopa** [comment]
Here you have the URL of the fields that are needed to post a Job

https://djopa.notion.site/Create-a-JobPost-721dfd81fb374f94b39ff61f7b2a727a

**Comment by wdjopa** [comment]
# Create a JobPost

## Add a Job

**FIELDS**

*Company name

*Company email (private, to send the invoice)

*Job name (Position)

*FullTime ? PartTime ?
*Job location (Remote, Country, City, etc)

Monthly salary range (MIN - MAX)

*Job Description

Benefits
How to apply

Apply url (email | phone | website)

Department

Tags (Custom tag/Technos/Frameworks) : dynamic field can use ([Select2.org](http://select2.org/))

**OPTIONS (with default checked)**

- [x]  Add company logo (+2.000XAF) [Allow the user to upload his logo]
- [x]  Diffusion on OSS Groups and accounts ( (8 x users in our databases) XAF)
- [x]  Personal notifications(Email & Telegram (JobSika Bot)) ( (15 x users in our databases) XAF)
- [ ]  Pin the Job offer on OSS Cameroon groups/account (+ 5.000XAF/week)
- [ ]  Pin the Job offer on Jobsika homepage (+10.000 XAF/week)
