### ISSUE TITLE
npm install giving unresolved dependencies

### ISSUE THREAD

**Issue by Eldrick19** [osscameroon/jobsika#396]
Hi 👋🏾 - I wanted to start contributing but am having trouble installing the project. When running npm install for the frontend, I get an unresolved dependency error for `webpack`:

<img width="562" alt="Capture d’écran, le 2023-05-04 à 22 20 16" src="https://user-images.githubusercontent.com/26189114/236365352-bea341ea-aedb-44a2-ba5e-89b4c4fc0408.png">

It looks like one of the CSS dependencies (`sass-loader`) is using webpack 5 when the app is meant to use webpack 4? Am I missing something? Might be a silly question but thanks for your patience :)

Steps to reproduce:
- Clone repo
- Go in `/frontend`
- Run npm install

npm version: 9.6.3

**Comment by elhmn** [comment]
Which version of node are you using ?

I think it is recommended to use nodejs 14 and above you can read more on this [readme](https://github.com/osscameroon/jobsika/tree/main/frontend#readme)

**Comment by Eldrick19** [comment]
Thank you, I missed that README. Closing the issue now as that solved the problem
