### ISSUE TITLE
Create job - form : typos fixes

### ISSUE THREAD

**Issue by wdjopa** [osscameroon/jobsika#403]
## Create a job form

1. "Job title" instead of "Job tittle"
![image](https://github.com/osscameroon/jobsika/assets/37931403/6a4ebf09-54ca-4d36-a150-27f921d767b0)

2. The description text is not correct I think
<img width="620" alt="Capture d’écran 2023-05-29 à 11 30 14" src="https://github.com/osscameroon/jobsika/assets/37931403/8bb03494-8dd2-428e-9f95-319d387d3525">

**Comment by Theryx** [comment]
Thanks for this, adjusted all changes
