### ISSUE TITLE
Estimate number of users

### ISSUE THREAD

**Issue by wdjopa** [osscameroon/jobsika#404]
Have an estimate of the number of users in our database to give the customer quantitative information.
<img width="816" alt="Capture d’écran 2023-05-29 à 11 13 55" src="https://github.com/osscameroon/jobsika/assets/37931403/bef06f15-3f44-471a-800a-082db081d8f9">

**Comment by Asam237** [comment]
this part will be removed for the time being

**Comment by elhmn** [comment]
We discussed about that during a telegram call, letting the user choose features add more complexity and than necessary at the stage of the project, where what is important for us is to validate that they would be willing to pay for that kind of services.

We would instead provide them with a single tier that will have some of the standard benefits we are already providing like sharing that job offer on our social media etc. And in the future that can be a list of multiple tiers having different benefits already preselected.

The conversation we had was captured on this issue https://github.com/osscameroon/jobsika/issues/366#issuecomment-1536778111
