### ISSUE TITLE
Make nav bar responsive on mobile

### ISSUE THREAD

**Issue by Theryx** [osscameroon/jobsika#436]
![Image](https://github.com/osscameroon/jobsika/assets/45546512/aa733ee9-61df-40e4-962b-00ba9f4c43f2)

**Comment by Asam237** [comment]
Je suis entrainde de travailler sur ce ticket.

**Comment by Theryx** [comment]
Alright so you are working without the design reference? 
Can I see what you are proposing so that I will not shift far from what you designed

**Comment by Asam237** [comment]
This ticket has been resolved => #442
